[colors-dark]
alpha=0.85
background=171d23
foreground=ffffff

## Normal/regular colors (color palette 0-7)
regular0=171d23  # black
regular1=ee3a43  # red
regular2=8bd49c  # green
regular3=d98e45  # yellow
regular4=539afc  # blue
regular5=b62d65  # magenta
regular6=52b8bf  # cyan
regular7=b7c5d3  # white

## Bright colors (color palette 8-15)
bright0=41505e   # bright black
bright1=d95468   # bright red
bright2=a0e3af   # bright green
bright3=ebbf83   # bright yellow
bright4=5ec4ff   # bright blue
bright5=e27e8d   # bright magenta
bright6=70e1e8   # bright cyan
bright7=ffffff   # bright white

